name: Daily Leaderboard Post

on:
  schedule:
     - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  post-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install discord.py Pillow requests python-dotenv apscheduler

      - name: Run daily post
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python daily_post.py
